name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Write Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOVELLO }}" > firebase-key.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: firebase-key.json
          channelId: live
          projectId: nifty-expanse-393415
